project_id = "imyzcwgskjngwvcadrjn"

[functions.resolve-bets]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false

[functions.calculate-weather-accuracy]
verify_jwt = false
